# # This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React Pull Request

on:
  pull_request:
    branches: [master, development]

env:
  BASE_RELEASE_VERSION: '1.0'

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node Packages
        run: npm install
      - name: Create Build
        run: npm run build --if-present
      - name: Run PR Tests with Coverage
        run: npm run test:pr
      - name: Run All Tests with Coverage
        run: npm run test:all
